hackathonapp/urls.py
from django.contrib import admin
from django.urls import include, path

from hackathonapp.views import dashboard

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("admin/", admin.site.urls),
    path("records/", include("records.urls")),
]

records/urls.py
from django.urls import path

from records.views import RecordDetailView, RecordListView

app_name = "records"
urlpatterns = [
    path("all/", RecordListView.as_view(), name="record-list"),
    path("<int:pk>/", RecordDetailView.as_view(), name="record-detail"),
]

records/models.py
from django.db import models


class Record(models.Model):
    name = models.CharField(unique=True, max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

hackathonapp/views.py
from django.shortcuts import render

from records.models import Record


def dashboard(request, *args, **kwargs):
    template = "hackathonapp/dashboard.html"
    data = {"records_total": Record.objects.count()}
    return render(request, template, data)

records/views.py
from django.views import generic

from records.models import Record


class RecordListView(generic.ListView):
    model = Record
    template_name = "records/record_list.html"


class RecordDetailView(generic.DetailView):
    model = Record
    template_name = "records/record_detail.html"

templates/hackathonapp/dashboard.html
{% load static %}
<link rel="stylesheet" href="{% static 'base.css' %}">

<h1>Welcome to Hackathon App!</h1>
<p>There are {{ records_total }} records in total.</p>
<p>To view a list of all records, click <a href="{% url 'records:record-list' %}">here</a>.</p>

templates/records/record_detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'base.css' %}">

<h1>Record: {{ object.name }}</h1>
<p>This record was created at: {{ object.created_at }}.</p>
<p>This record was last modified at: {{ object.last_modified_at }}.</p>
<p>Go back to see <a href="{% url 'records:record-list' %}">all records</a>.</p>

templates/records/record_list.html
{% load static %}
<link rel="stylesheet" href="{% static 'base.css' %}">

<h1>All records</h1>
<ul>
    {% for record in object_list %}
        <li>
            <p>Name: {{ record.name }}</p>
            <p>Created at: {{ record.created_at }}</p>
            <p>Last modified at: {{ record.last_modified_at }}</p>
            <p>Click <a href="{% url 'records:record-detail' record.pk %}">here</a> for more details.</p>
        </li>
    {% endfor %}
</ul>
<p>Go back to the <a href="{% url 'dashboard' %}">dashboard</a>.</p>